export enum EventTypeEnum {
  EVENT1 = 'EVENT1',
  EVENT2 = 'EVENT2',
  EVENT3 = 'EVENT3',
  EVENT4 = 'EVENT4',
  EVENT5 = 'EVENT5',
  EVENT6 = 'EVENT6',
  EVENT7 = 'EVENT7',
  EVENT8 = 'EVENT8',
  EVENT9 = 'EVENT9',
  EVENT10 = 'EVENT10',
}
